name: xgboost-1.0.2-cuda-10.1
channels:
    - conda-forge
    - defaults
    - rapidsai
dependencies:
    - defaults::click=7.1.1
    - defaults::cudatoolkit=10.1
    - conda-forge::dask==2.14.0
    - rapidsai::dask-cuda==0.13.0
    - conda-forge::graphviz=2.40.1
    - conda-forge::python-graphviz=0.13.2
    - conda-forge::scikit-learn==0.22.1
    - pip
    - pip:
    #  - xgboost==1.0.2 # xgboost on Conda is not yet built with GPU support!
    #   https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/list.html
    #  - https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/xgboost-1.1.0_SNAPSHOT%2B86beb68ce8ffa73a90def6a9862f0e8a917b58c3-py2.py3-none-manylinux1_x86_64.whl
      - xgboost==1.1.0rc2
