name: xgboost-1.0.2-cuda-10.1
channels:
    - conda-forge
    - defaults
dependencies:
    - defaults::click=7.1.1
    - defaults::cudatoolkit=10.1
    - conda-forge::graphviz=2.40.1
    - conda-forge::python-graphviz=0.13.2
    - conda-forge::scikit-learn==0.22.1
    - pip
    - pip:
      - xgboost==1.0.2 # xgboost on Conda is not yet built with GPU support!
